### ISSUE TITLE
This Vape has a back door   这个Vape有后门

### ISSUE THREAD

**Issue by DreamsMMM** [RandomVapeUser/Vape-4.16#5]

**Comment by DreamsMMM** [comment]
This is an inspection： 
这是检查:               
https://www.virustotal.com/gui/file/2babfc51e39dd5e17fd33a74f2938c71eeb9a91e5430833b8e693f8a0fbcc5d5/detection

**Comment by DreamsMMM** [comment]
This is an inspection：
这是检查:
https://www.virustotal.com/gui/file/319a145536f32881604eaf8ed2a20de6d2f496ff5229d9ad92eafc64314acf64

**Comment by DreamsMMM** [comment]
New Fix（新的修复版）:https://www.mediafire.com/file/584zmdfpkz18l1f/anything_meow.rar/file

password(密码):meow

**Comment by DreamsMMM** [comment]
中国人请使用此链接：https://wwt.lanzoue.com/iZJAD275frqd

**Comment by RandomVapeUser** [comment]
Ok I will look into it thanks and Il see about the one you sent me

**Comment by DreamsMMM** [comment]
> Ok I will look into it thanks and Il see about the one you sent me

OK, Thank You.I hope you can fix it and publish it on Github.Thank You!

**Comment by bilibiliLXZY** [comment]
Your vape have backdoor so DreamsMMM fucked you😡😡

**Comment by RandomVapeUser** [comment]
real

**Comment by RandomVapeUser** [comment]
![image](https://github.com/user-attachments/assets/f44f52db-9528-46b7-8e44-cc6f9d27e138)
what your fixed version gives me

**Comment by infamouskoala** [comment]
> Your vape have backdoor so DreamsMMM fucked you😡😡

hi sir, here are a few corrections I'd like to add in ur comment:
- "Your vape" he did not code this client
- "have backdoor" is an incorrect sentence, it should be "has a backdoor"
- "DreamsMMM fucked you" IDK who that is but he is NOT fucking anyone though his monitor.

Have a nice day!

**Comment by bilibiliLXZY** [comment]
> > Your vape have backdoor so DreamsMMM fucked you😡😡
> 
> hi sir, here are a few corrections I'd like to add in ur comment:
> 
> * "Your vape" he did not code this client
> * "have backdoor" is an incorrect sentence, it should be "has a backdoor"
> * "DreamsMMM fucked you" IDK who that is but he is NOT fucking anyone though his monitor.
> 
> Have a nice day!

Sorry, I didn't ponder :|
and I'm chinese

**Comment by RandomVapeUser** [comment]
no way bro folded to koala just like that
